//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.20 at 06:38:06 PM CET 
//


package it.polito.dp2.BIB.sol1.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.polito.dp2.BIB.sol1.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.polito.dp2.BIB.sol1.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MyBiblio }
     * 
     */
    public MyBiblio createMyBiblio() {
        return new MyBiblio();
    }

    /**
     * Create an instance of {@link MyBookType }
     * 
     */
    public MyBookType createMyBookType() {
        return new MyBookType();
    }

    /**
     * Create an instance of {@link MyArticleType }
     * 
     */
    public MyArticleType createMyArticleType() {
        return new MyArticleType();
    }

    /**
     * Create an instance of {@link MyJournalType }
     * 
     */
    public MyJournalType createMyJournalType() {
        return new MyJournalType();
    }

    /**
     * Create an instance of {@link MyBiblioItemType }
     * 
     */
    public MyBiblioItemType createMyBiblioItemType() {
        return new MyBiblioItemType();
    }

    /**
     * Create an instance of {@link MyIssueType }
     * 
     */
    public MyIssueType createMyIssueType() {
        return new MyIssueType();
    }

}
